# Generated by Django 5.1.2 on 2024-10-08 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Semi-novo', 'Semi-novo'), ('Recondicionado', 'Recondicionado'), ('Danificado', 'Danificado')], max_length=20)),
                ('category', models.CharField(choices=[('Roupas', 'Roupas'), ('Moveis', 'Móveis'), ('Eletrodomesticos', 'Eletrodomésticos'), ('Brinquedos', 'Brinquedos'), ('Livros', 'Livros'), ('Informatica', 'Informática'), ('Esportes', 'Esportes'), ('Ferramentas', 'Ferramentas'), ('Cosmeticos', 'Cosméticos')], max_length=20)),
                ('images', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('endereco', models.CharField(blank=True, max_length=100)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='icon-profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
