# Generated by Django 5.1.1 on 2024-10-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_product_cep_profile_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
